'''
convert reflectSuppress results back to hierachical folder format

steps:
    1. put all .png results generated by matlab in ./results
    2. run this script python res2folder.py
'''

import numpy as np
from glob import glob
import cv2
import os

results_dir = './results'
files = glob(results_dir+'/*')
count = 0
for file in files:
    im = cv2.imread(file,-1) # read 16 bit png

    new_name = file.replace('-', '/')
    if not os.path.exists(new_name[:-12]):
        os.makedirs(new_name[:-12])
    # save 16 bit png
    cv2.imwrite(new_name, im)
    count += 1
print("done {} files".format(count))
